name: SimplyChat
version: 1.0.0
api-version: 1.19
main: cx.leo.simplychat.SimplyChat
description: "Modern Chat plugin utilizing the PaperAPI and MiniMessage features with easy configuration."
authors: ['ItsSimplyLeo']
website: "https://github.com/ItsSimplyLeo/SimplyChat"

softdepend:
  - 'Vault'